=== achref-thamri/gymdeck-exercises/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "pattern": "^[A-Za-z0-9][A-Za-z0-9_.-]*$"
        },
        "name": {
            "type": "string",
            "minLength": 1
        },
        "muscles": {
            "type": "object",
            "properties": {
                "primary": {
                    "type": "string",
                    "enum": [
                        "chest",
                        "back",
                        "shoulders",
                        "biceps",
                        "triceps",
                        "quads",
                        "hamstrings",
                        "glutes",
                        "calves",
                        "abs"
                    ]
                },
                "secondary": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "chest",
                            "back",
                            "shoulders",
                            "biceps",
                            "triceps",
                            "quads",
                            "hamstrings",
                            "glutes",
                            "calves",
                            "abs"
                        ]
                    }
                }
            },
            "required": [
                "primary",
                "secondary"
            ],
            "additionalProperties": false
        },
        "equipment": {
            "minItems": 1,
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "bodyweight",
                    "dumbbell",
                    "barbell",
                    "kettlebell",
                    "cable",
                    "band",
                    "pullup-bar",
                    "bench",
                    "chest-press-machine",
                    "pec-deck",
                    "lat-pulldown",
                    "seated-row-machine",
                    "shoulder-press-machine",
                    "leg-press",
                    "leg-extension",
                    "leg-curl",
                    "smith-machine",
                    "hip-thrust-machine",
                    "calf-raise-machine"
                ]
            }
        },
        "mechanic": {
            "type": "string",
            "enum": [
                "compound",
                "isolation"
            ]
        },
        "level": {
            "type": "string",
            "enum": [
                "beginner",
                "intermediate",
                "expert"
            ]
        },
        "steps": {
            "minItems": 2,
            "type": "array",
            "items": {
                "type": "string",
                "minLength": 1
            }
        },
        "tips": {
            "minItems": 1,
            "type": "array",
            "items": {
                "type": "string",
                "minLength": 1
            }
        },
        "source": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "minLength": 1
                },
                "id": {
                    "type": "string",
                    "minLength": 1
                }
            },
            "required": [
                "name",
                "id"
            ],
            "additionalProperties": false
        },
        "$schema": {
            "type": "string"
        }
    },
    "required": [
        "id",
        "name",
        "muscles",
        "equipment",
        "mechanic",
        "level",
        "steps"
    ],
    "additionalProperties": false
}

=== achref-thamri/gymdeck-exercises/exercises/Seated_Flat_Bench_Leg_Pull-In.json
{
    "$schema": "../schema.json",
    "id": "Seated_Flat_Bench_Leg_Pull-In",
    "name": "Seated Flat Bench Leg Pull-In",
    "muscles": {
        "primary": "abs",
        "secondary": []
    },
    "equipment": ["bench"],
    "mechanic": "compound",
    "level": "beginner",
    "steps": [
        "Sit on a bench with the legs stretched out in front of you slightly below parallel and your arms holding on to the sides of the bench. Your torso should be leaning backwards around a 45-degree angle from the bench. This will be your starting position.",
        "Bring the knees in toward you as you move your torso closer to them at the same time. Breathe out as you perform this movement.",
        "After a second pause, go back to the starting position as you inhale.",
        "Repeat for the recommended amount of repetitions."
    ]
}

=== achref-thamri/gymdeck-exercises/exercises/Reverse_Crunch.json
{
    "$schema": "../schema.json",
    "id": "Reverse_Crunch",
    "name": "Reverse Crunch",
    "muscles": {
        "primary": "abs",
        "secondary": []
    },
    "equipment": ["bodyweight"],
    "mechanic": "isolation",
    "level": "beginner",
    "steps": [
        "Lie down on the floor with your legs fully extended and arms to the side of your torso with the palms on the floor. Your arms should be stationary for the entire exercise.",
        "Move your legs up so that your thighs are perpendicular to the floor and feet are together and parallel to the floor. This is the starting position.",
        "While inhaling, move your legs towards the torso as you roll your pelvis backwards and you raise your hips off the floor. At the end of this movement your knees will be touching your chest.",
        "Hold the contraction for a second and move your legs back to the starting position while exhaling.",
        "Repeat for the recommended amount of repetitions."
    ],
    "source": {
        "name": "free-exercise-db",
        "id": "Reverse_Crunch"
    }
}

=== achref-thamri/gymdeck-exercises/exercises/Barbell_Deadlift.json
{
    "$schema": "../schema.json",
    "id": "Barbell_Deadlift",
    "name": "Barbell Deadlift",
    "muscles": {
        "primary": "back",
        "secondary": ["calves", "glutes", "hamstrings", "quads"]
    },
    "equipment": ["barbell"],
    "mechanic": "compound",
    "level": "intermediate",
    "steps": [
        "Stand in front of a loaded barbell.",
        "While keeping the back as straight as possible, bend your knees, bend forward and grasp the bar using a medium (shoulder width) overhand grip. This will be the starting position of the exercise. Tip: If it is difficult to hold on to the bar with this grip, alternate your grip or use wrist straps.",
        "While holding the bar, start the lift by pushing with your legs while simultaneously getting your torso to the upright position as you breathe out. In the upright position, stick your chest out and contract the back by bringing the shoulder blades back. Think of how the soldiers in the military look when they are in standing in attention.",
        "Go back to the starting position by bending at the knees while simultaneously leaning the torso forward at the waist while keeping the back straight. When the weights on the bar touch the floor you are back at the starting position and ready to perform another repetition.",
        "Perform the amount of repetitions prescribed in the program."
    ]
}

=== achref-thamri/gymdeck-exercises/exercises/Lying_Dumbbell_Tricep_Extension.json
{
    "$schema": "../schema.json",
    "id": "Lying_Dumbbell_Tricep_Extension",
    "name": "Lying Dumbbell Tricep Extension",
    "muscles": {
        "primary": "triceps",
        "secondary": ["chest", "shoulders"]
    },
    "equipment": ["dumbbell"],
    "mechanic": "isolation",
    "level": "intermediate",
    "steps": [
        "Lie on a flat bench while holding two dumbbells directly in front of you. Your arms should be fully extended at a 90-degree angle from your torso and the floor. The palms should be facing in and the elbows should be tucked in. This is the starting position.",
        "As you breathe in and you keep the upper arms stationary with the elbows in, slowly lower the weight until the dumbbells are near your ears.",
        "At that point, while keeping the elbows in and the upper arms stationary, use the triceps to bring the weight back up to the starting position as you breathe out.",
        "Repeat for the recommended amount of repetitions."
    ]
}

=== achref-thamri/gymdeck-exercises/exercises/Upright_Cable_Row.json
{
    "$schema": "../schema.json",
    "id": "Upright_Cable_Row",
    "name": "Upright Cable Row",
    "muscles": {
        "primary": "back",
        "secondary": ["shoulders"]
    },
    "equipment": ["cable"],
    "mechanic": "compound",
    "level": "intermediate",
    "steps": [
        "Grasp a straight bar cable attachment that is attached to a low pulley with a pronated (palms facing your thighs) grip that is slightly less than shoulder width. The bar should be resting on top of your thighs. Your arms should be extended with a slight bend at the elbows and your back should be straight. This will be your starting position.",
        "Use your side shoulders to lift the cable bar as you exhale. The bar should be close to the body as you move it up. Continue to lift it until it nearly touches your chin. Tip: Your elbows should drive the motion. As you lift the bar, your elbows should always be higher than your forearms. Also, keep your torso stationary and pause for a second at the top of the movement.",
        "Lower the bar back down slowly to the starting position. Inhale as you perform this portion of the movement.",
        "Repeat for the recommended amount of repetitions."
    ],
    "source": {
        "name": "free-exercise-db",
        "id": "Upright_Cable_Row"
    }
}

=== achref-thamri/gymdeck-exercises/exercises/Cable_Reverse_Crunch.json
{
    "$schema": "../schema.json",
    "id": "Cable_Reverse_Crunch",
    "name": "Cable Reverse Crunch",
    "muscles": {
        "primary": "abs",
        "secondary": []
    },
    "equipment": ["cable"],
    "mechanic": "isolation",
    "level": "beginner",
    "steps": [
        "Connect an ankle strap attachment to a low pulley cable and position a mat on the floor in front of it.",
        "Sit down with your feet toward the pulley and attach the cable to your ankles.",
        "Lie down, elevate your legs and bend your knees at a 90-degree angle. Your legs and the cable should be aligned. If not, adjust the pulley up or down until they are.",
        "With your hands behind your head, bring your knees inward to your torso and elevate your hips off the floor.",
        "Pause for a moment and in a slow and controlled manner drop your hips and bring your legs back to the starting 90-degree angle. You should still have tension on your abs in the resting position.",
        "Repeat the same movement to failure."
    ],
    "source": {
        "name": "free-exercise-db",
        "id": "Cable_Reverse_Crunch"
    }
}

=== achref-thamri/gymdeck-exercises/exercises/leg-press.json
{
    "$schema": "../schema.json",
    "id": "leg-press",
    "name": "Leg press",
    "muscles": {
        "primary": "quads",
        "secondary": ["glutes"]
    },
    "equipment": ["leg-press"],
    "mechanic": "compound",
    "level": "beginner",
    "steps": [
        "Using a leg press machine, sit down on the machine and place your legs on the platform directly in front of you at a medium (shoulder width) foot stance. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section).",
        "Lower the safety bars holding the weighted platform in place and press the platform all the way up until your legs are fully extended in front of you. Tip: Make sure that you do not lock your knees. Your torso and the legs should make a perfect 90-degree angle. This will be your starting position.",
        "As you inhale, slowly lower the platform until your upper and lower legs make a 90-degree angle.",
        "Pushing mainly with the heels of your feet and using the quadriceps go back to the starting position as you exhale.",
        "Repeat for the recommended amount of repetitions and ensure to lock the safety pins properly once you are done. You do not want that platform falling on you fully loaded."
    ],
    "tips": ["Lower back stays on the pad."],
    "source": {
        "name": "free-exercise-db",
        "id": "Leg_Press"
    }
}

=== achref-thamri/gymdeck-exercises/exercises/bench-dip.json
{
    "$schema": "../schema.json",
    "id": "bench-dip",
    "name": "Bench dip",
    "muscles": {
        "primary": "triceps",
        "secondary": ["chest"]
    },
    "equipment": ["bench"],
    "mechanic": "compound",
    "level": "beginner",
    "steps": [
        "For this exercise you will need to place a bench behind your back. With the bench perpendicular to your body, and while looking away from it, hold on to the bench on its edge with the hands fully extended, separated at shoulder width. The legs will be extended forward, bent at the waist and perpendicular to your torso. This will be your starting position.",
        "Slowly lower your body as you inhale by bending at the elbows until you lower yourself far enough to where there is an angle slightly smaller than 90 degrees between the upper arm and the forearm. Tip: Keep the elbows as close as possible throughout the movement. Forearms should always be pointing down.",
        "Using your triceps to bring your torso up again, lift yourself back to the starting position.",
        "Repeat for the recommended amount of repetitions."
    ],
    "tips": ["Keep the back close to the bench."],
    "source": {
        "name": "free-exercise-db",
        "id": "Bench_Dips"
    }
}
